feature/18 into develop
LVMVRQUXL/CGG pull request #27
Opened 2020-11-23 22:18 UTC by Taiyang999

Fixes #18

2020-11-23 22:19 UTC, Taiyang999 commented
Sur mon tél du coups Honor 8X :
![image](https://user-images.githubusercontent.com/56363037/100021764-477a7a80-2de2-11eb-8abd-9d35d2dd7188.png)

2020-11-25 09:30 UTC, LVMVRQUXL requested changes
Bravo pour ton travail !
Tu trouveras ci-dessous les modifications à apporter à ta branche.

2020-11-25 09:30 UTC, LVMVRQUXL commented on app/src/main/res/values/ids.xml
> +</resources>
A quoi le fichier `ids.xml` sert ?

2020-11-25 09:30 UTC, LVMVRQUXL commented on app/src/main/res/values/strings.xml
> +    <string name="question">What\'s the background color ?</string>
La question ne correspond pas à la maquette ! 😉
Tu sais quoi faire.

2020-11-25 10:52 UTC, Taiyang999 commented on app/src/main/res/values/ids.xml
> +</resources>
Je pense que ça a été géneré lorsque je testais les fonctions avec du Kotlin. Je crois que j'avais "item" lorsque je manipulais une liste. Je vais la delete pour cette feature

2020-11-25 10:52 UTC, Taiyang999 commented on app/src/main/res/values/strings.xml
> +    <string name="question">What\'s the background color ?</string>
😉

2020-11-26 18:16 UTC, LVMVRQUXL approved these changes
PR validée : je la fusionne !

2020-11-26 18:18 UTC, merged