Feature/38 into develop
LVMVRQUXL/CGG pull request #57
Opened 2021-01-21 21:15 UTC by iReiki

Fixes #38

2021-01-21 21:16 UTC, iReiki commented
![image](https://user-images.githubusercontent.com/43532134/105413388-52ad2380-5c36-11eb-8533-60b300ebb5bd.png)

2021-01-22 18:01 UTC, LVMVRQUXL requested changes
Bon dans l'ensemble, mais malgré un développement rapide, il y a des choses à corriger avant de fusionner la fonctionnalité (dont une erreur qui fait crasher l'application au démarrage).

2021-01-22 18:01 UTC, LVMVRQUXL commented on app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
> +            lastScoreText?.text = "Last score :"
Il faut mettre le texte dans les ressources `strings.xml` !

2021-01-22 18:01 UTC, LVMVRQUXL commented on app/src/main/java/fr/esgi/rpa/cgg/result/ResultActivity.kt
> +    private var roundsNumber: String? = ""
Initialise plutôt tes variables à `null` si tu leur donnes un type *nullable*.

2021-01-22 18:01 UTC, LVMVRQUXL commented on app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
> +                val roundsNumber = fullScore[1].toInt()
Je ne sais pas si tu as essayé de lancer l'application pendant ton développement, mais cette ligne fait crasher l'application dès son lancement : `java.lang.IndexOutOfBoundsException: Index: 1, Size: 1`...

2021-01-22 18:06 UTC, iReiki commented on app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
> +                val roundsNumber = fullScore[1].toInt()
Ah ouais ? Mince, moi ça plantait pas dans mon cas mais je vais éditer ça, merci de ton retour

2021-01-22 18:29 UTC, iReiki commented on app/src/main/java/fr/esgi/rpa/cgg/score/ScoresCsvManager.kt
> +                val roundsNumber = fullScore[1].toInt()
Par contre chez moi ça fonctionne vraiment, j'ai aucune erreur

2021-01-22 18:30 UTC, iReiki commented on app/src/main/java/fr/esgi/rpa/cgg/MainActivity.kt
> +            lastScoreText?.text = "Last score :"
C'est fait, merci pour le retour !

2021-01-22 23:24 UTC, LVMVRQUXL approved these changes
PR validée !

2021-01-22 23:26 UTC, merged